/**
 * Sound design layer — places synthesized SFX at precise frame offsets
 * across all scenes using Remotion's <Audio> + <Sequence>.
 *
 * Audio files live in public/sfx/ and are generated by scripts/generate-sfx.mjs
 */

import React from 'react';
import { Audio, Sequence, staticFile } from 'remotion';
import { scenes } from '../lib/timing';

// ── Asset paths ──────────────────────────────────────────
const sfx = {
  tap:     staticFile('sfx/tap.wav'),
  click:   staticFile('sfx/click.wav'),
  pop:     staticFile('sfx/pop.wav'),
  whoosh:  staticFile('sfx/whoosh.wav'),
  chime:   staticFile('sfx/chime.wav'),
  ping:    staticFile('sfx/ping.wav'),
  success: staticFile('sfx/success.wav'),
  pad:     staticFile('sfx/pad.wav'),
  music:   staticFile('sfx/music.wav'),
};

/** Helper: place an audio clip at a specific absolute frame.
 *  showInTimeline=false avoids the Studio waveform visualizer which
 *  can throw IndexSizeError on very short audio files. */
const SFX: React.FC<{
  src: string;
  frame: number;
  volume?: number;
  playbackRate?: number;
}> = ({ src, frame, volume = 1, playbackRate = 1 }) => (
  <Sequence from={frame} durationInFrames={60} showInTimeline={false}>
    <Audio src={src} volume={volume} playbackRate={playbackRate} showInTimeline={false} />
  </Sequence>
);

export const SoundLayer: React.FC = () => {
  const s = scenes;

  return (
    <>
      {/* ═══════ Scene 1: Narrative (660f) — panel transitions ═══════ */}
      {/* Panel 1 fade in */}
      <SFX src={sfx.whoosh} frame={s.pain.start + 5} volume={0.06} playbackRate={0.8} />
      {/* Panel 2 (details) */}
      <SFX src={sfx.whoosh} frame={s.pain.start + 140} volume={0.06} playbackRate={0.9} />
      {/* Panel 3 (the quote) */}
      <SFX src={sfx.whoosh} frame={s.pain.start + 280} volume={0.07} playbackRate={0.9} />
      {/* Panel 4 (supporting pain) */}
      <SFX src={sfx.ping} frame={s.pain.start + 440} volume={0.06} />
      {/* Panel 5 (the trigger) */}
      <SFX src={sfx.chime} frame={s.pain.start + 570} volume={0.08} />

      {/* ═══════ Scene 2: Website + Click (150f) ═══════ */}
      <SFX src={sfx.click} frame={s.click.start + 115} volume={0.03} />
      <SFX src={sfx.pop} frame={s.click.start + 120} volume={0.05} />
      <SFX src={sfx.whoosh} frame={s.click.start + 130} volume={0.04} />

      {/* ═══════ Scene 3: Self-Assessment (330f) — chip selections ═══════ */}
      {/* Beat A: Module selections (sped up) */}
      <SFX src={sfx.pop} frame={s.conversation.start + 15} volume={0.03} />
      <SFX src={sfx.pop} frame={s.conversation.start + 30} volume={0.03} />
      <SFX src={sfx.pop} frame={s.conversation.start + 42} volume={0.03} />

      {/* Beat B: Pain point selections */}
      <SFX src={sfx.pop} frame={s.conversation.start + 70} volume={0.03} playbackRate={0.9} />
      <SFX src={sfx.pop} frame={s.conversation.start + 85} volume={0.03} playbackRate={0.9} />
      <SFX src={sfx.pop} frame={s.conversation.start + 98} volume={0.03} playbackRate={0.9} />

      {/* Beat C: Report + data access selections */}
      <SFX src={sfx.pop} frame={s.conversation.start + 125} volume={0.02} playbackRate={1.1} />
      <SFX src={sfx.pop} frame={s.conversation.start + 135} volume={0.02} playbackRate={1.1} />

      {/* Beat D: Final selections */}
      <SFX src={sfx.pop} frame={s.conversation.start + 162} volume={0.02} />
      <SFX src={sfx.pop} frame={s.conversation.start + 170} volume={0.02} />

      {/* Chat messages appear */}
      <SFX src={sfx.tap} frame={s.conversation.start + 195} volume={0.03} />
      <SFX src={sfx.tap} frame={s.conversation.start + 225} volume={0.03} />
      <SFX src={sfx.tap} frame={s.conversation.start + 255} volume={0.03} />
      <SFX src={sfx.tap} frame={s.conversation.start + 285} volume={0.03} />

      {/* ═══════ Scene 4: Spec + Wedge (300f) ═══════ */}
      <SFX src={sfx.click} frame={s.wow.start + 5} volume={0.03} />
      {/* Spec sections appear */}
      {[10, 25, 40, 55, 70].map((f) => (
        <SFX key={`spec-${f}`} src={sfx.click} frame={s.wow.start + f} volume={0.02} playbackRate={1.2} />
      ))}
      {/* Wedge recommendation slides in */}
      <SFX src={sfx.chime} frame={s.wow.start + 85} volume={0.05} />
      {/* SAP table pills pop in */}
      {[105, 110, 115, 120, 125].map((f) => (
        <SFX key={`pill-${f}`} src={sfx.pop} frame={s.wow.start + f} volume={0.02} playbackRate={1.3} />
      ))}
      {/* Timeline appears */}
      <SFX src={sfx.ping} frame={s.wow.start + 130} volume={0.03} />
      {/* Expert Review button */}
      <SFX src={sfx.ping} frame={s.wow.start + 165} volume={0.04} />
      {/* "Before any sales call" overlay */}
      <SFX src={sfx.success} frame={s.wow.start + 235} volume={0.06} />

      {/* ═══════ Scene 5: Pipeline Zoom Out (420f) ═══════ */}
      {/* Overlay beat 1 */}
      <SFX src={sfx.whoosh} frame={s.zoomOut.start + 5} volume={0.05} />
      {/* Overlay beat 2 */}
      <SFX src={sfx.chime} frame={s.zoomOut.start + 80} volume={0.05} />
      {/* Pipeline fades in */}
      <SFX src={sfx.chime} frame={s.zoomOut.start + 140} volume={0.04} />
      {/* Staggered card entrances (at 155 + i*8) */}
      {[155, 163, 171, 179, 187, 195].map((f, i) => (
        <SFX key={`card-${f}`} src={sfx.click} frame={s.zoomOut.start + f} volume={0.02} playbackRate={0.8 + i * 0.05} />
      ))}
      {/* Flash-expand clicks (at 210 + i*30) */}
      {[210, 240, 270, 300, 330, 360].map((f) => (
        <SFX key={`flash-${f}`} src={sfx.click} frame={s.zoomOut.start + f} volume={0.02} playbackRate={1.4} />
      ))}

      {/* ═══════ Scene 6: Knowledge Loop (180f) ═══════ */}
      <SFX src={sfx.ping} frame={s.loop.start + 5} volume={0.07} />
      <SFX src={sfx.whoosh} frame={s.loop.start + 10} volume={0.07} playbackRate={0.6} />
      <SFX src={sfx.ping} frame={s.loop.start + 55} volume={0.07} playbackRate={0.85} />
      <SFX src={sfx.pop} frame={s.loop.start + 82} volume={0.06} />
      <SFX src={sfx.pop} frame={s.loop.start + 90} volume={0.06} />
      <SFX src={sfx.chime} frame={s.loop.start + 118} volume={0.07} />

      {/* ═══════ Scene 7: CTA (180f) ═══════ */}
      <SFX src={sfx.chime} frame={s.cta.start + 5} volume={0.08} playbackRate={0.9} />
      <SFX src={sfx.ping} frame={s.cta.start + 85} volume={0.06} />

      {/* ═══════ Ambient pad ═══════ */}
      {/* Scene 1 (dark narrative) */}
      <Sequence from={s.pain.start} durationInFrames={s.pain.duration} showInTimeline={false}>
        <Audio src={sfx.pad} volume={0.12} showInTimeline={false} />
      </Sequence>

      {/* ═══════ Background music — full duration ═══════ */}
      <Sequence from={0} durationInFrames={2190} showInTimeline={false}>
        <Audio src={sfx.music} volume={0.18} showInTimeline={false} />
      </Sequence>
    </>
  );
};
