/**
 * Sound design layer — places synthesized SFX at precise frame offsets
 * across all scenes using Remotion's <Audio> + <Sequence>.
 *
 * Audio files live in public/sfx/ and are generated by scripts/generate-sfx.mjs
 */

import React from 'react';
import { Audio, Sequence, staticFile } from 'remotion';
import { scenes } from '../lib/timing';

// ── Asset paths ──────────────────────────────────────────
const sfx = {
  tap:     staticFile('sfx/tap.wav'),
  click:   staticFile('sfx/click.wav'),
  pop:     staticFile('sfx/pop.wav'),
  whoosh:  staticFile('sfx/whoosh.wav'),
  chime:   staticFile('sfx/chime.wav'),
  ping:    staticFile('sfx/ping.wav'),
  success: staticFile('sfx/success.wav'),
  pad:     staticFile('sfx/pad.wav'),
};

/** Helper: place an audio clip at a specific absolute frame.
 *  showInTimeline=false avoids the Studio waveform visualizer which
 *  can throw IndexSizeError on very short audio files. */
const SFX: React.FC<{
  src: string;
  frame: number;
  volume?: number;
  playbackRate?: number;
}> = ({ src, frame, volume = 1, playbackRate = 1 }) => (
  <Sequence from={frame} durationInFrames={60} showInTimeline={false}>
    <Audio src={src} volume={volume} playbackRate={playbackRate} showInTimeline={false} />
  </Sequence>
);

export const SoundLayer: React.FC = () => {
  const s = scenes;

  return (
    <>
      {/* ═══════ Scene 1: Narrative (270f) — panel transitions ═══════ */}
      {/* Panel 1 fade in */}
      <SFX src={sfx.whoosh} frame={s.pain.start + 5} volume={0.2} playbackRate={0.8} />
      {/* Panel 2 (the pain) */}
      <SFX src={sfx.whoosh} frame={s.pain.start + 80} volume={0.25} playbackRate={0.9} />
      {/* Panel 3 (the trigger) */}
      <SFX src={sfx.chime} frame={s.pain.start + 160} volume={0.25} />

      {/* ═══════ Scene 2: Website + Click (90f) ═══════ */}
      <SFX src={sfx.click} frame={s.click.start + 42} volume={0.2} />
      <SFX src={sfx.pop} frame={s.click.start + 50} volume={0.5} />
      <SFX src={sfx.whoosh} frame={s.click.start + 60} volume={0.35} />

      {/* ═══════ Scene 3: Self-Assessment (270f) — chip selections ═══════ */}
      {/* Beat A: Module selections at frames 20, 40, 55 */}
      <SFX src={sfx.pop} frame={s.conversation.start + 20} volume={0.35} />
      <SFX src={sfx.pop} frame={s.conversation.start + 40} volume={0.35} />
      <SFX src={sfx.pop} frame={s.conversation.start + 55} volume={0.35} />

      {/* Beat B: Pain point selections at 75+15, 75+35, 75+50 */}
      <SFX src={sfx.pop} frame={s.conversation.start + 90} volume={0.3} playbackRate={0.9} />
      <SFX src={sfx.pop} frame={s.conversation.start + 110} volume={0.3} playbackRate={0.9} />
      <SFX src={sfx.pop} frame={s.conversation.start + 125} volume={0.3} playbackRate={0.9} />

      {/* Beat C: Report + data access selections */}
      <SFX src={sfx.pop} frame={s.conversation.start + 168} volume={0.25} playbackRate={1.1} />
      <SFX src={sfx.pop} frame={s.conversation.start + 180} volume={0.25} playbackRate={1.1} />
      <SFX src={sfx.pop} frame={s.conversation.start + 190} volume={0.25} playbackRate={1.1} />

      {/* Beat D: Final selections + compress */}
      <SFX src={sfx.pop} frame={s.conversation.start + 222} volume={0.25} />
      <SFX src={sfx.pop} frame={s.conversation.start + 232} volume={0.25} />
      <SFX src={sfx.whoosh} frame={s.conversation.start + 250} volume={0.4} />

      {/* ═══════ Scene 4: Spec + Wedge (270f) ═══════ */}
      <SFX src={sfx.click} frame={s.wow.start + 5} volume={0.2} />
      {/* Spec sections appear */}
      {[10, 25, 40, 55, 70].map((f) => (
        <SFX key={`spec-${f}`} src={sfx.click} frame={s.wow.start + f} volume={0.15} playbackRate={1.2} />
      ))}
      {/* Wedge recommendation slides in */}
      <SFX src={sfx.chime} frame={s.wow.start + 85} volume={0.35} />
      {/* SAP table pills pop in */}
      {[105, 110, 115, 120, 125].map((f) => (
        <SFX key={`pill-${f}`} src={sfx.pop} frame={s.wow.start + f} volume={0.2} playbackRate={1.3} />
      ))}
      {/* Timeline appears */}
      <SFX src={sfx.ping} frame={s.wow.start + 130} volume={0.2} />
      {/* Expert Review button */}
      <SFX src={sfx.ping} frame={s.wow.start + 158} volume={0.25} />
      {/* "Before any sales call" overlay */}
      <SFX src={sfx.success} frame={s.wow.start + 218} volume={0.4} />

      {/* ═══════ Scene 5: Pipeline Zoom Out (360f) ═══════ */}
      {/* Overlay text appears */}
      <SFX src={sfx.whoosh} frame={s.zoomOut.start + 5} volume={0.3} />
      {/* Pipeline fades in */}
      <SFX src={sfx.chime} frame={s.zoomOut.start + 80} volume={0.2} />
      {/* Staggered card entrances (at 90 + i*8) */}
      {[90, 98, 106, 114, 122, 130].map((f, i) => (
        <SFX key={`card-${f}`} src={sfx.click} frame={s.zoomOut.start + f} volume={0.18} playbackRate={0.8 + i * 0.05} />
      ))}
      {/* Flash-expand clicks (at 150 + i*30) */}
      {[150, 180, 210, 240, 270, 300].map((f) => (
        <SFX key={`flash-${f}`} src={sfx.click} frame={s.zoomOut.start + f} volume={0.12} playbackRate={1.4} />
      ))}

      {/* ═══════ Scene 6: Knowledge Loop (150f) ═══════ */}
      <SFX src={sfx.ping} frame={s.loop.start + 5} volume={0.3} />
      <SFX src={sfx.whoosh} frame={s.loop.start + 10} volume={0.3} playbackRate={0.6} />
      <SFX src={sfx.ping} frame={s.loop.start + 45} volume={0.3} playbackRate={0.85} />
      <SFX src={sfx.pop} frame={s.loop.start + 72} volume={0.3} />
      <SFX src={sfx.pop} frame={s.loop.start + 78} volume={0.3} />
      <SFX src={sfx.chime} frame={s.loop.start + 102} volume={0.3} />

      {/* ═══════ Scene 7: CTA (90f) ═══════ */}
      <SFX src={sfx.chime} frame={s.cta.start + 5} volume={0.25} playbackRate={0.9} />
      <SFX src={sfx.ping} frame={s.cta.start + 48} volume={0.2} />

      {/* ═══════ Ambient pad ═══════ */}
      {/* Scene 1 (dark narrative) */}
      <Sequence from={s.pain.start} durationInFrames={s.pain.duration} showInTimeline={false}>
        <Audio src={sfx.pad} volume={0.15} showInTimeline={false} />
      </Sequence>
    </>
  );
};
